export const API_URL = process.env.NEXT_PUBLIC_API_URL || "https://your-api-endpoint.com/v1"
export const APP_ENV = process.env.NEXT_PUBLIC_APP_ENV || "development"
export const COOKIE_DOMAIN = process.env.NEXT_PUBLIC_COOKIE_DOMAIN || "localhost"
export const COOKIE_PREFIX = process.env.NEXT_PUBLIC_COOKIE_PREFIX || "admin"
export const APP_DOMAIN = process.env.NEXT_PUBLIC_APP_DOMAIN || "localhost"